/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package examen1p2_fernandopadilla;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Wendy
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    ArrayList<Equipo> equipos = new ArrayList();
    ArrayList<Estadio> estadios = new ArrayList();
    ArrayList<Jugador> jugadores = new ArrayList();

    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedpane = new javax.swing.JTabbedPane();
        panel_AgregarJ = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        tf_nombreJ = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tf_edadJ = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tf_nacionalidadJ = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tf_pieH = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cb_equipoJugador = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        cb_posicion = new javax.swing.JComboBox<>();
        btn_agregarJ = new javax.swing.JButton();
        panel_ModificarJ = new javax.swing.JPanel();
        panel_EliminarJ = new javax.swing.JPanel();
        cb_eliminarJ = new javax.swing.JComboBox<>();
        btn_eliminarJ = new javax.swing.JButton();
        panel_ListarJ = new javax.swing.JPanel();
        panel_AgregarEq = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf_nombreEquipo = new javax.swing.JTextField();
        tf_paisEquipo = new javax.swing.JTextField();
        jb_crearEq = new javax.swing.JButton();
        panel_ModificarEq = new javax.swing.JPanel();
        panel_EliminarEq = new javax.swing.JPanel();
        panel_ListarEq = new javax.swing.JPanel();
        panel_AgregarEs = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tf_nombreEstadio = new javax.swing.JTextField();
        tf_ciudadEstadio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tf_capacidadE = new javax.swing.JTextField();
        cb_equipos = new javax.swing.JComboBox<>();
        btn_crearEs = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        panel_ModificarEs = new javax.swing.JPanel();
        panel_EliminarEs = new javax.swing.JPanel();
        cb_eliminarEs = new javax.swing.JComboBox<>();
        bt_elminarEs = new javax.swing.JButton();
        panel_ListarEs = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_AgregarJ.setBackground(new java.awt.Color(102, 102, 102));

        jLabel7.setText("Nombre de Jugador");

        jLabel8.setText("Edad");

        jLabel9.setText("Nacionalidad");

        jLabel10.setText("Pie Habil");

        jLabel11.setText("Equipo");

        jLabel12.setText("Posicion");

        cb_posicion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Portero", "Defensa", "Mediocampista", "Delantero" }));

        btn_agregarJ.setText("Agregar");
        btn_agregarJ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_agregarJMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_AgregarJLayout = new javax.swing.GroupLayout(panel_AgregarJ);
        panel_AgregarJ.setLayout(panel_AgregarJLayout);
        panel_AgregarJLayout.setHorizontalGroup(
            panel_AgregarJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_AgregarJLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(panel_AgregarJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_agregarJ, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_AgregarJLayout.createSequentialGroup()
                        .addGroup(panel_AgregarJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panel_AgregarJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_nombreJ)
                            .addComponent(tf_edadJ)
                            .addComponent(tf_nacionalidadJ)
                            .addComponent(tf_pieH)
                            .addComponent(cb_equipoJugador, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cb_posicion, 0, 200, Short.MAX_VALUE))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        panel_AgregarJLayout.setVerticalGroup(
            panel_AgregarJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_AgregarJLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(panel_AgregarJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tf_nombreJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_AgregarJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tf_edadJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_AgregarJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tf_nacionalidadJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_AgregarJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tf_pieH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_AgregarJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cb_equipoJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_AgregarJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cb_posicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_agregarJ, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        tabbedpane.addTab("A.Jugador", panel_AgregarJ);

        panel_ModificarJ.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout panel_ModificarJLayout = new javax.swing.GroupLayout(panel_ModificarJ);
        panel_ModificarJ.setLayout(panel_ModificarJLayout);
        panel_ModificarJLayout.setHorizontalGroup(
            panel_ModificarJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 682, Short.MAX_VALUE)
        );
        panel_ModificarJLayout.setVerticalGroup(
            panel_ModificarJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 439, Short.MAX_VALUE)
        );

        tabbedpane.addTab("M.Jugador", panel_ModificarJ);

        panel_EliminarJ.setBackground(new java.awt.Color(102, 102, 102));

        btn_eliminarJ.setText("Eliminar");
        btn_eliminarJ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_eliminarJMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_EliminarJLayout = new javax.swing.GroupLayout(panel_EliminarJ);
        panel_EliminarJ.setLayout(panel_EliminarJLayout);
        panel_EliminarJLayout.setHorizontalGroup(
            panel_EliminarJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_EliminarJLayout.createSequentialGroup()
                .addGroup(panel_EliminarJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_EliminarJLayout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(cb_eliminarJ, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_EliminarJLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btn_eliminarJ, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        panel_EliminarJLayout.setVerticalGroup(
            panel_EliminarJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_EliminarJLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(cb_eliminarJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btn_eliminarJ, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        tabbedpane.addTab("E. Jugador", panel_EliminarJ);

        javax.swing.GroupLayout panel_ListarJLayout = new javax.swing.GroupLayout(panel_ListarJ);
        panel_ListarJ.setLayout(panel_ListarJLayout);
        panel_ListarJLayout.setHorizontalGroup(
            panel_ListarJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 682, Short.MAX_VALUE)
        );
        panel_ListarJLayout.setVerticalGroup(
            panel_ListarJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 439, Short.MAX_VALUE)
        );

        tabbedpane.addTab("L. Jugador", panel_ListarJ);

        panel_AgregarEq.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setText("Nombre del Equipo");

        jLabel2.setText("Pais del Equipo");

        jb_crearEq.setText("Crear");
        jb_crearEq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_crearEqMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_AgregarEqLayout = new javax.swing.GroupLayout(panel_AgregarEq);
        panel_AgregarEq.setLayout(panel_AgregarEqLayout);
        panel_AgregarEqLayout.setHorizontalGroup(
            panel_AgregarEqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_AgregarEqLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(panel_AgregarEqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(panel_AgregarEqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_nombreEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_paisEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_AgregarEqLayout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(jb_crearEq, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        panel_AgregarEqLayout.setVerticalGroup(
            panel_AgregarEqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_AgregarEqLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(panel_AgregarEqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(tf_nombreEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_AgregarEqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_paisEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addComponent(jb_crearEq, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        tabbedpane.addTab("A. Equipo", panel_AgregarEq);

        javax.swing.GroupLayout panel_ModificarEqLayout = new javax.swing.GroupLayout(panel_ModificarEq);
        panel_ModificarEq.setLayout(panel_ModificarEqLayout);
        panel_ModificarEqLayout.setHorizontalGroup(
            panel_ModificarEqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 682, Short.MAX_VALUE)
        );
        panel_ModificarEqLayout.setVerticalGroup(
            panel_ModificarEqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 439, Short.MAX_VALUE)
        );

        tabbedpane.addTab("M. Equipo", panel_ModificarEq);

        javax.swing.GroupLayout panel_EliminarEqLayout = new javax.swing.GroupLayout(panel_EliminarEq);
        panel_EliminarEq.setLayout(panel_EliminarEqLayout);
        panel_EliminarEqLayout.setHorizontalGroup(
            panel_EliminarEqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 682, Short.MAX_VALUE)
        );
        panel_EliminarEqLayout.setVerticalGroup(
            panel_EliminarEqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 439, Short.MAX_VALUE)
        );

        tabbedpane.addTab("E. Equipo", panel_EliminarEq);

        javax.swing.GroupLayout panel_ListarEqLayout = new javax.swing.GroupLayout(panel_ListarEq);
        panel_ListarEq.setLayout(panel_ListarEqLayout);
        panel_ListarEqLayout.setHorizontalGroup(
            panel_ListarEqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 682, Short.MAX_VALUE)
        );
        panel_ListarEqLayout.setVerticalGroup(
            panel_ListarEqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 439, Short.MAX_VALUE)
        );

        tabbedpane.addTab("L. Equipo", panel_ListarEq);

        panel_AgregarEs.setBackground(new java.awt.Color(102, 102, 102));

        jLabel3.setText("Nombre del Estadio");

        jLabel4.setText("Ciudad del Estadio");

        jLabel5.setText("Capacidad Estadio");

        btn_crearEs.setText("Crear Estadio");
        btn_crearEs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_crearEsMouseClicked(evt);
            }
        });

        jLabel6.setText("Club Propietario");

        javax.swing.GroupLayout panel_AgregarEsLayout = new javax.swing.GroupLayout(panel_AgregarEs);
        panel_AgregarEs.setLayout(panel_AgregarEsLayout);
        panel_AgregarEsLayout.setHorizontalGroup(
            panel_AgregarEsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_AgregarEsLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(panel_AgregarEsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_crearEs, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_AgregarEsLayout.createSequentialGroup()
                        .addGroup(panel_AgregarEsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addGroup(panel_AgregarEsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(panel_AgregarEsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_capacidadE, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_nombreEstadio, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_ciudadEstadio, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_equipos, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        panel_AgregarEsLayout.setVerticalGroup(
            panel_AgregarEsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_AgregarEsLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(panel_AgregarEsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(tf_nombreEstadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_AgregarEsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_ciudadEstadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(panel_AgregarEsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_capacidadE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_AgregarEsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_equipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(29, 29, 29)
                .addComponent(btn_crearEs, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        tabbedpane.addTab("A. Estadio", panel_AgregarEs);

        javax.swing.GroupLayout panel_ModificarEsLayout = new javax.swing.GroupLayout(panel_ModificarEs);
        panel_ModificarEs.setLayout(panel_ModificarEsLayout);
        panel_ModificarEsLayout.setHorizontalGroup(
            panel_ModificarEsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 682, Short.MAX_VALUE)
        );
        panel_ModificarEsLayout.setVerticalGroup(
            panel_ModificarEsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 439, Short.MAX_VALUE)
        );

        tabbedpane.addTab("M. Estadio", panel_ModificarEs);

        panel_EliminarEs.setBackground(new java.awt.Color(102, 102, 102));

        bt_elminarEs.setText("Eliminar");

        javax.swing.GroupLayout panel_EliminarEsLayout = new javax.swing.GroupLayout(panel_EliminarEs);
        panel_EliminarEs.setLayout(panel_EliminarEsLayout);
        panel_EliminarEsLayout.setHorizontalGroup(
            panel_EliminarEsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_EliminarEsLayout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(cb_eliminarEs, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_EliminarEsLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(bt_elminarEs, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        panel_EliminarEsLayout.setVerticalGroup(
            panel_EliminarEsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_EliminarEsLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(cb_eliminarEs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bt_elminarEs, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        tabbedpane.addTab("E. Estadio", panel_EliminarEs);

        javax.swing.GroupLayout panel_ListarEsLayout = new javax.swing.GroupLayout(panel_ListarEs);
        panel_ListarEs.setLayout(panel_ListarEsLayout);
        panel_ListarEsLayout.setHorizontalGroup(
            panel_ListarEsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 682, Short.MAX_VALUE)
        );
        panel_ListarEsLayout.setVerticalGroup(
            panel_ListarEsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 439, Short.MAX_VALUE)
        );

        tabbedpane.addTab("L. Estadio", panel_ListarEs);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedpane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedpane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public DefaultComboBoxModel actualizarComboEquipo(JComboBox cb){
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        
        for (Equipo t : equipos) {
            modelo.addElement(t);
        }
        return modelo;
    }
    
    public DefaultComboBoxModel actualizarComboJugador(JComboBox cb){
         DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        
        for (Jugador t : jugadores) {
            modelo.addElement(t);
        }
        return modelo;
    }
    
    public DefaultComboBoxModel actualizarComboEstadio(JComboBox cb){
         DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        
        for (Estadio t : estadios) {
            modelo.addElement(t);
        }
        return modelo;
    }
    
    private void jb_crearEqMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_crearEqMouseClicked

        if (tf_nombreEquipo.getText().equals("") || tf_paisEquipo.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Ingrese todos los atributos");
            tf_nombreEquipo.setText("");
            tf_paisEquipo.setText("");
        } else {
            String nombreE = tf_nombreEquipo.getText();
            String paisE = tf_paisEquipo.getText();
            tf_nombreEquipo.setText("");
            tf_paisEquipo.setText("");
            equipos.add(new Equipo(nombreE, paisE));
            JOptionPane.showMessageDialog(this, "Equipo agregado exitosamente");
            cb_equipos.setModel(actualizarComboEquipo(cb_equipos));
        }
    }//GEN-LAST:event_jb_crearEqMouseClicked

    private void btn_crearEsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_crearEsMouseClicked
        if (tf_nombreEstadio.getText().equals("") 
                || tf_ciudadEstadio.getText().equals("") 
                || tf_capacidadE.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Ingrese todos los atributos");
            tf_nombreEstadio.setText("");
            tf_ciudadEstadio.setText("");
            tf_capacidadE.setText("");
        }else{
            String nombreE = tf_nombreEstadio.getText();
            String ciudad = tf_ciudadEstadio.getText();
            int capacidad = Integer.parseInt(tf_capacidadE.getText());
            Equipo equipoP = equipos.get(cb_equipos.getSelectedIndex());
            estadios.add(new Estadio(nombreE, ciudad, capacidad, equipoP));
            JOptionPane.showMessageDialog(this, "Agregado con exito");
            tf_nombreEstadio.setText("");
            tf_ciudadEstadio.setText("");
            tf_capacidadE.setText("");
            cb_eliminarEs.setModel(actualizarComboEstadio(cb_eliminarEs));
        }
    }//GEN-LAST:event_btn_crearEsMouseClicked

    private void btn_agregarJMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_agregarJMouseClicked
        if (tf_nombreJ.getText().equals("")
                ||tf_edadJ.getText().equals("")
                ||tf_nacionalidadJ.getText().equals("")
                ||tf_pieH.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Ingrese todos los atributos");
            tf_nombreJ.setText("");
            tf_edadJ.setText("");
            tf_nacionalidadJ.setText("");
            tf_pieH.setText("");
        }else{
            String nombreJ = tf_nombreJ.getText();
            int edad = Integer.parseInt(tf_edadJ.getText());
            String nacionalidad = tf_nacionalidadJ.getText();
            String pieH = tf_pieH.getText();
            Equipo equipo = equipos.get(cb_equipoJugador.getSelectedIndex());
            if (equipo.getPlantilla().size() < 4) {
               if (cb_posicion.getSelectedIndex() == 0) {
                Portero portero = new Portero(nombreJ, edad, nacionalidad, pieH, equipo);
                jugadores.add(portero);
                equipos.get(cb_equipoJugador.getSelectedIndex()).getPlantilla().add(portero);
                JOptionPane.showMessageDialog(this, "Portero agregado");
            }else if(cb_posicion.getSelectedIndex() == 1){
                Defensa defensa = new Defensa(nombreJ, edad, nacionalidad, pieH, equipo);
                jugadores.add(defensa);
                equipos.get(cb_equipoJugador.getSelectedIndex()).getPlantilla().add(defensa);
                JOptionPane.showMessageDialog(this, "Defensa agregado");
            }else if(cb_posicion.getSelectedIndex() == 2){
                MedioCampista mediocampista = new MedioCampista(nombreJ, edad, nacionalidad, pieH, equipo);
                jugadores.add(mediocampista);
                equipos.get(cb_equipoJugador.getSelectedIndex()).getPlantilla().add(mediocampista);
                JOptionPane.showMessageDialog(this, "Mediocampista agregado");
            }else if(cb_posicion.getSelectedIndex() == 3){
                Delantero delantero = new Delantero(nombreJ, edad, nacionalidad, pieH, equipo);
                jugadores.add(delantero);
                equipos.get(cb_equipoJugador.getSelectedIndex()).getPlantilla().add(delantero);
                JOptionPane.showMessageDialog(this, "Delantero agregado con exito");
            } 
            }else{
                JOptionPane.showMessageDialog(this, "Este equipo ya esta lleno");
            }
            
        }
    }//GEN-LAST:event_btn_agregarJMouseClicked

    private void btn_eliminarJMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_eliminarJMouseClicked
        if (cb_eliminarEs.getSelectedIndex() >= 0) {
            estadios.remove(cb_eliminarEs.getSelectedIndex());
            JOptionPane.showMessageDialog(this, "Eliminado con exito");
        }
    }//GEN-LAST:event_btn_eliminarJMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_elminarEs;
    private javax.swing.JButton btn_agregarJ;
    private javax.swing.JButton btn_crearEs;
    private javax.swing.JButton btn_eliminarJ;
    private javax.swing.JComboBox<String> cb_eliminarEs;
    private javax.swing.JComboBox<String> cb_eliminarJ;
    private javax.swing.JComboBox<String> cb_equipoJugador;
    private javax.swing.JComboBox<String> cb_equipos;
    private javax.swing.JComboBox<String> cb_posicion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jb_crearEq;
    private javax.swing.JPanel panel_AgregarEq;
    private javax.swing.JPanel panel_AgregarEs;
    private javax.swing.JPanel panel_AgregarJ;
    private javax.swing.JPanel panel_EliminarEq;
    private javax.swing.JPanel panel_EliminarEs;
    private javax.swing.JPanel panel_EliminarJ;
    private javax.swing.JPanel panel_ListarEq;
    private javax.swing.JPanel panel_ListarEs;
    private javax.swing.JPanel panel_ListarJ;
    private javax.swing.JPanel panel_ModificarEq;
    private javax.swing.JPanel panel_ModificarEs;
    private javax.swing.JPanel panel_ModificarJ;
    private javax.swing.JTabbedPane tabbedpane;
    private javax.swing.JTextField tf_capacidadE;
    private javax.swing.JTextField tf_ciudadEstadio;
    private javax.swing.JTextField tf_edadJ;
    private javax.swing.JTextField tf_nacionalidadJ;
    private javax.swing.JTextField tf_nombreEquipo;
    private javax.swing.JTextField tf_nombreEstadio;
    private javax.swing.JTextField tf_nombreJ;
    private javax.swing.JTextField tf_paisEquipo;
    private javax.swing.JTextField tf_pieH;
    // End of variables declaration//GEN-END:variables
}
