/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package examen1p2_fernandopadilla;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Wendy
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    ArrayList<Equipo> equipos = new ArrayList();
    ArrayList<Estadio> estadios = new ArrayList();
    ArrayList<Jugador> jugadores = new ArrayList();

    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedpane = new javax.swing.JTabbedPane();
        panel_AgregarJ = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        tf_nombreJ = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tf_edadJ = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tf_nacionalidadJ = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tf_pieH = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cb_equipoJugador = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        cb_posicion = new javax.swing.JComboBox<>();
        btn_agregarJ = new javax.swing.JButton();
        panel_ModificarJ = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        tf_nombreJ1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        tf_edadJ1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        tf_nacionalidadJ1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        tf_pieH1 = new javax.swing.JTextField();
        btn_modificarJ = new javax.swing.JButton();
        cb_modificarJ = new javax.swing.JComboBox<>();
        panel_EliminarJ = new javax.swing.JPanel();
        cb_eliminarJ = new javax.swing.JComboBox<>();
        btn_eliminarJ = new javax.swing.JButton();
        panel_ListarJ = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Table_jugador = new javax.swing.JTable();
        bt_actualizarJugador = new javax.swing.JButton();
        panel_AgregarEq = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf_nombreEquipo = new javax.swing.JTextField();
        tf_paisEquipo = new javax.swing.JTextField();
        jb_crearEq = new javax.swing.JButton();
        panel_ModificarEq = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tf_nombreEquipo1 = new javax.swing.JTextField();
        tf_paisEquipo1 = new javax.swing.JTextField();
        bt_modificarEq = new javax.swing.JButton();
        cb_modificarEq = new javax.swing.JComboBox<>();
        panel_EliminarEq = new javax.swing.JPanel();
        cb_eliminarEq = new javax.swing.JComboBox<>();
        bt_elminarEq = new javax.swing.JButton();
        panel_ListarEq = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table_equipo = new javax.swing.JTable();
        bt_actualizarEquipo = new javax.swing.JButton();
        panel_AgregarEs = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tf_nombreEstadio = new javax.swing.JTextField();
        tf_ciudadEstadio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tf_capacidadE = new javax.swing.JTextField();
        cb_equipos = new javax.swing.JComboBox<>();
        btn_crearEs = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        panel_ModificarEs = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        tf_nombreEstadio1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        tf_ciudadEstadio1 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        tf_capacidadE1 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        cb_equipos1 = new javax.swing.JComboBox<>();
        btn_modificarEs = new javax.swing.JButton();
        cb_modificarEs = new javax.swing.JComboBox<>();
        panel_EliminarEs = new javax.swing.JPanel();
        cb_eliminarEs = new javax.swing.JComboBox<>();
        bt_elminarEs = new javax.swing.JButton();
        panel_ListarEs = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_estadio = new javax.swing.JTable();
        bt_actualizarEstadio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_AgregarJ.setBackground(new java.awt.Color(102, 102, 102));

        jLabel7.setText("Nombre de Jugador");

        jLabel8.setText("Edad");

        jLabel9.setText("Nacionalidad");

        jLabel10.setText("Pie Habil");

        jLabel11.setText("Equipo");

        jLabel12.setText("Posicion");

        cb_posicion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Portero", "Defensa", "Mediocampista", "Delantero" }));

        btn_agregarJ.setText("Agregar");
        btn_agregarJ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_agregarJMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_AgregarJLayout = new javax.swing.GroupLayout(panel_AgregarJ);
        panel_AgregarJ.setLayout(panel_AgregarJLayout);
        panel_AgregarJLayout.setHorizontalGroup(
            panel_AgregarJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_AgregarJLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(panel_AgregarJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_agregarJ, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_AgregarJLayout.createSequentialGroup()
                        .addGroup(panel_AgregarJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panel_AgregarJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_nombreJ)
                            .addComponent(tf_edadJ)
                            .addComponent(tf_nacionalidadJ)
                            .addComponent(tf_pieH)
                            .addComponent(cb_equipoJugador, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cb_posicion, 0, 200, Short.MAX_VALUE))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        panel_AgregarJLayout.setVerticalGroup(
            panel_AgregarJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_AgregarJLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(panel_AgregarJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tf_nombreJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_AgregarJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tf_edadJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_AgregarJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tf_nacionalidadJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_AgregarJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tf_pieH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_AgregarJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cb_equipoJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_AgregarJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cb_posicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_agregarJ, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        tabbedpane.addTab("A.Jugador", panel_AgregarJ);

        panel_ModificarJ.setBackground(new java.awt.Color(102, 102, 102));

        jLabel15.setText("Nombre de Jugador");

        jLabel16.setText("Edad");

        jLabel17.setText("Nacionalidad");

        jLabel18.setText("Pie Habil");

        btn_modificarJ.setText("Modificar");
        btn_modificarJ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_modificarJMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_ModificarJLayout = new javax.swing.GroupLayout(panel_ModificarJ);
        panel_ModificarJ.setLayout(panel_ModificarJLayout);
        panel_ModificarJLayout.setHorizontalGroup(
            panel_ModificarJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ModificarJLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(panel_ModificarJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_modificarJ, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_ModificarJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(cb_modificarJ, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_ModificarJLayout.createSequentialGroup()
                            .addGroup(panel_ModificarJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel15)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel17)
                                .addComponent(jLabel18))
                            .addGap(18, 18, 18)
                            .addGroup(panel_ModificarJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tf_nombreJ1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                .addComponent(tf_edadJ1)
                                .addComponent(tf_nacionalidadJ1)
                                .addComponent(tf_pieH1)))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        panel_ModificarJLayout.setVerticalGroup(
            panel_ModificarJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ModificarJLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(cb_modificarJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panel_ModificarJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(tf_nombreJ1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_ModificarJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(tf_edadJ1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_ModificarJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(tf_nacionalidadJ1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_ModificarJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(tf_pieH1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(btn_modificarJ, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        tabbedpane.addTab("M.Jugador", panel_ModificarJ);

        panel_EliminarJ.setBackground(new java.awt.Color(102, 102, 102));

        btn_eliminarJ.setText("Eliminar");
        btn_eliminarJ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_eliminarJMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_EliminarJLayout = new javax.swing.GroupLayout(panel_EliminarJ);
        panel_EliminarJ.setLayout(panel_EliminarJLayout);
        panel_EliminarJLayout.setHorizontalGroup(
            panel_EliminarJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_EliminarJLayout.createSequentialGroup()
                .addGroup(panel_EliminarJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_EliminarJLayout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(cb_eliminarJ, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_EliminarJLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btn_eliminarJ, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_EliminarJLayout.setVerticalGroup(
            panel_EliminarJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_EliminarJLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(cb_eliminarJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btn_eliminarJ, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        tabbedpane.addTab("E. Jugador", panel_EliminarJ);

        Table_jugador.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Edad", "Nacionalidad", "Pie Habil", "Rating", "Equipo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(Table_jugador);

        bt_actualizarJugador.setText("Actualizar");
        bt_actualizarJugador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_actualizarJugadorMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_ListarJLayout = new javax.swing.GroupLayout(panel_ListarJ);
        panel_ListarJ.setLayout(panel_ListarJLayout);
        panel_ListarJLayout.setHorizontalGroup(
            panel_ListarJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_ListarJLayout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(bt_actualizarJugador)
                .addGap(54, 54, 54)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panel_ListarJLayout.setVerticalGroup(
            panel_ListarJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ListarJLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_ListarJLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_actualizarJugador)
                .addGap(206, 206, 206))
        );

        tabbedpane.addTab("L. Jugador", panel_ListarJ);

        panel_AgregarEq.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setText("Nombre del Equipo");

        jLabel2.setText("Pais del Equipo");

        jb_crearEq.setText("Crear");
        jb_crearEq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_crearEqMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_AgregarEqLayout = new javax.swing.GroupLayout(panel_AgregarEq);
        panel_AgregarEq.setLayout(panel_AgregarEqLayout);
        panel_AgregarEqLayout.setHorizontalGroup(
            panel_AgregarEqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_AgregarEqLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(panel_AgregarEqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(panel_AgregarEqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_nombreEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_paisEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_AgregarEqLayout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(jb_crearEq, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        panel_AgregarEqLayout.setVerticalGroup(
            panel_AgregarEqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_AgregarEqLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(panel_AgregarEqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(tf_nombreEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_AgregarEqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_paisEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addComponent(jb_crearEq, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        tabbedpane.addTab("A. Equipo", panel_AgregarEq);

        panel_ModificarEq.setBackground(new java.awt.Color(102, 102, 102));

        jLabel13.setText("Nombre del Equipo");

        jLabel14.setText("Pais del Equipo");

        bt_modificarEq.setText("Modificar");
        bt_modificarEq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_modificarEqMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_ModificarEqLayout = new javax.swing.GroupLayout(panel_ModificarEq);
        panel_ModificarEq.setLayout(panel_ModificarEqLayout);
        panel_ModificarEqLayout.setHorizontalGroup(
            panel_ModificarEqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_ModificarEqLayout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(bt_modificarEq, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
            .addGroup(panel_ModificarEqLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(panel_ModificarEqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cb_modificarEq, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panel_ModificarEqLayout.createSequentialGroup()
                        .addGroup(panel_ModificarEqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(panel_ModificarEqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_nombreEquipo1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_paisEquipo1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_ModificarEqLayout.setVerticalGroup(
            panel_ModificarEqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ModificarEqLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(cb_modificarEq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(panel_ModificarEqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(tf_nombreEquipo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_ModificarEqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tf_paisEquipo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addComponent(bt_modificarEq, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        tabbedpane.addTab("M. Equipo", panel_ModificarEq);

        panel_EliminarEq.setBackground(new java.awt.Color(102, 102, 102));

        bt_elminarEq.setText("Eliminar");
        bt_elminarEq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_elminarEqMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_EliminarEqLayout = new javax.swing.GroupLayout(panel_EliminarEq);
        panel_EliminarEq.setLayout(panel_EliminarEqLayout);
        panel_EliminarEqLayout.setHorizontalGroup(
            panel_EliminarEqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_EliminarEqLayout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(cb_eliminarEq, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_EliminarEqLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(bt_elminarEq, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        panel_EliminarEqLayout.setVerticalGroup(
            panel_EliminarEqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_EliminarEqLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(cb_eliminarEq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bt_elminarEq, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        tabbedpane.addTab("E. Equipo", panel_EliminarEq);

        Table_equipo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Pais", "Rating"
            }
        ));
        jScrollPane2.setViewportView(Table_equipo);

        bt_actualizarEquipo.setText("Actualizar");
        bt_actualizarEquipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_actualizarEquipoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_ListarEqLayout = new javax.swing.GroupLayout(panel_ListarEq);
        panel_ListarEq.setLayout(panel_ListarEqLayout);
        panel_ListarEqLayout.setHorizontalGroup(
            panel_ListarEqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_ListarEqLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(bt_actualizarEquipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        panel_ListarEqLayout.setVerticalGroup(
            panel_ListarEqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_ListarEqLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(panel_ListarEqLayout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(bt_actualizarEquipo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabbedpane.addTab("L. Equipo", panel_ListarEq);

        panel_AgregarEs.setBackground(new java.awt.Color(102, 102, 102));

        jLabel3.setText("Nombre del Estadio");

        jLabel4.setText("Ciudad del Estadio");

        jLabel5.setText("Capacidad Estadio");

        btn_crearEs.setText("Crear Estadio");
        btn_crearEs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_crearEsMouseClicked(evt);
            }
        });

        jLabel6.setText("Club Propietario");

        javax.swing.GroupLayout panel_AgregarEsLayout = new javax.swing.GroupLayout(panel_AgregarEs);
        panel_AgregarEs.setLayout(panel_AgregarEsLayout);
        panel_AgregarEsLayout.setHorizontalGroup(
            panel_AgregarEsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_AgregarEsLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(panel_AgregarEsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_crearEs, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_AgregarEsLayout.createSequentialGroup()
                        .addGroup(panel_AgregarEsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addGroup(panel_AgregarEsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(panel_AgregarEsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_capacidadE, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_nombreEstadio, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_ciudadEstadio, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_equipos, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        panel_AgregarEsLayout.setVerticalGroup(
            panel_AgregarEsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_AgregarEsLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(panel_AgregarEsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(tf_nombreEstadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_AgregarEsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_ciudadEstadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(panel_AgregarEsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_capacidadE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_AgregarEsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_equipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(29, 29, 29)
                .addComponent(btn_crearEs, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        tabbedpane.addTab("A. Estadio", panel_AgregarEs);

        panel_ModificarEs.setBackground(new java.awt.Color(102, 102, 102));

        jLabel19.setText("Nombre del Estadio");

        jLabel20.setText("Ciudad del Estadio");

        jLabel21.setText("Capacidad Estadio");

        jLabel22.setText("Club Propietario");

        btn_modificarEs.setText("Modificar Estadio");
        btn_modificarEs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_modificarEsMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_ModificarEsLayout = new javax.swing.GroupLayout(panel_ModificarEs);
        panel_ModificarEs.setLayout(panel_ModificarEsLayout);
        panel_ModificarEsLayout.setHorizontalGroup(
            panel_ModificarEsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ModificarEsLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(panel_ModificarEsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_modificarEs, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_ModificarEsLayout.createSequentialGroup()
                        .addGroup(panel_ModificarEsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addGroup(panel_ModificarEsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(panel_ModificarEsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_capacidadE1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_nombreEstadio1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_ciudadEstadio1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_equipos1, 0, 324, Short.MAX_VALUE)
                            .addComponent(cb_modificarEs, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        panel_ModificarEsLayout.setVerticalGroup(
            panel_ModificarEsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ModificarEsLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(cb_modificarEs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panel_ModificarEsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel19)
                    .addComponent(tf_nombreEstadio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_ModificarEsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(tf_ciudadEstadio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(panel_ModificarEsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(tf_capacidadE1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_ModificarEsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_equipos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(29, 29, 29)
                .addComponent(btn_modificarEs, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        tabbedpane.addTab("M. Estadio", panel_ModificarEs);

        panel_EliminarEs.setBackground(new java.awt.Color(102, 102, 102));

        bt_elminarEs.setText("Eliminar");
        bt_elminarEs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_elminarEsMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_EliminarEsLayout = new javax.swing.GroupLayout(panel_EliminarEs);
        panel_EliminarEs.setLayout(panel_EliminarEsLayout);
        panel_EliminarEsLayout.setHorizontalGroup(
            panel_EliminarEsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_EliminarEsLayout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(cb_eliminarEs, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_EliminarEsLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(bt_elminarEs, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        panel_EliminarEsLayout.setVerticalGroup(
            panel_EliminarEsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_EliminarEsLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(cb_eliminarEs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bt_elminarEs, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        tabbedpane.addTab("E. Estadio", panel_EliminarEs);

        Table_estadio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Ciudad", "Capacidad", "Equipo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Table_estadio);

        bt_actualizarEstadio.setText("Actualizar");
        bt_actualizarEstadio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_actualizarEstadioMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_ListarEsLayout = new javax.swing.GroupLayout(panel_ListarEs);
        panel_ListarEs.setLayout(panel_ListarEsLayout);
        panel_ListarEsLayout.setHorizontalGroup(
            panel_ListarEsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_ListarEsLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(bt_actualizarEstadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        panel_ListarEsLayout.setVerticalGroup(
            panel_ListarEsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ListarEsLayout.createSequentialGroup()
                .addGroup(panel_ListarEsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_ListarEsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_ListarEsLayout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(bt_actualizarEstadio)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabbedpane.addTab("L. Estadio", panel_ListarEs);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedpane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedpane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public DefaultComboBoxModel actualizarComboEquipo() {
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();

        for (Equipo t : equipos) {
            modelo.addElement(t);
        }
        return modelo;
    }

    public DefaultComboBoxModel actualizarComboJugador() {
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();

        for (Jugador t : jugadores) {
            modelo.addElement(t);
        }
        return modelo;
    }

    public DefaultComboBoxModel actualizarComboEstadio() {
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();

        for (Estadio t : estadios) {
            modelo.addElement(t);
        }
        return modelo;
    }

    public DefaultTableModel actualizarTablaJugador(DefaultTableModel tm) {
        DefaultTableModel modelo = tm;
        for (Jugador t : jugadores) {
            Object[] row = {t.getNombre(), t.getEdad(), t.getNacionalidad(), t.getPieH(), t.getRating(), t.getEquipo().getNombre()};
            modelo.addRow(row);
        }
        return modelo;
    }

    public DefaultTableModel actualizarTablaEquipo(DefaultTableModel tm) {
        DefaultTableModel modelo = tm;
        for (Equipo t : equipos) {
            Object[] row = {t.getNombre(), t.getPais(), t.getRating()};
            modelo.addRow(row);
        }
        return modelo;
    }

    public DefaultTableModel actualizarTablaEstadio(DefaultTableModel tm) {
        DefaultTableModel modelo = tm;
        for (Estadio t : estadios) {
            Object[] row = {};
            modelo.addRow(row);
        }
        return modelo;
    }

    private void jb_crearEqMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_crearEqMouseClicked

        if (tf_nombreEquipo.getText().equals("") || tf_paisEquipo.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Ingrese todos los atributos");
            tf_nombreEquipo.setText("");
            tf_paisEquipo.setText("");
        } else {
            String nombreE = tf_nombreEquipo.getText();
            String paisE = tf_paisEquipo.getText();
            tf_nombreEquipo.setText("");
            tf_paisEquipo.setText("");
            equipos.add(new Equipo(nombreE, paisE));
            JOptionPane.showMessageDialog(this, "Equipo agregado exitosamente");
            cb_equipos.setModel(actualizarComboEquipo());
            cb_modificarEq.setModel(actualizarComboEquipo());
            cb_eliminarEq.setModel(actualizarComboEquipo());
            cb_equipos1.setModel(actualizarComboEquipo());
        }
    }//GEN-LAST:event_jb_crearEqMouseClicked

    private void btn_crearEsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_crearEsMouseClicked
        if (tf_nombreEstadio.getText().equals("")
                || tf_ciudadEstadio.getText().equals("")
                || tf_capacidadE.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Ingrese todos los atributos");
            tf_nombreEstadio.setText("");
            tf_ciudadEstadio.setText("");
            tf_capacidadE.setText("");
        } else {
            String nombreE = tf_nombreEstadio.getText();
            String ciudad = tf_ciudadEstadio.getText();
            int capacidad = Integer.parseInt(tf_capacidadE.getText());
            Equipo equipoP = equipos.get(cb_equipos.getSelectedIndex());
            estadios.add(new Estadio(nombreE, ciudad, capacidad, equipoP));
            JOptionPane.showMessageDialog(this, "Agregado con exito");
            tf_nombreEstadio.setText("");
            tf_ciudadEstadio.setText("");
            tf_capacidadE.setText("");
            cb_eliminarEs.setModel(actualizarComboEstadio());

        }
    }//GEN-LAST:event_btn_crearEsMouseClicked

    private void btn_agregarJMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_agregarJMouseClicked
        if (tf_nombreJ.getText().equals("")
                || tf_edadJ.getText().equals("")
                || tf_nacionalidadJ.getText().equals("")
                || tf_pieH.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Ingrese todos los atributos");
            tf_nombreJ.setText("");
            tf_edadJ.setText("");
            tf_nacionalidadJ.setText("");
            tf_pieH.setText("");
        } else {
            String nombreJ = tf_nombreJ.getText();
            int edad = Integer.parseInt(tf_edadJ.getText());
            String nacionalidad = tf_nacionalidadJ.getText();
            String pieH = tf_pieH.getText();
            Equipo equipo = equipos.get(cb_equipoJugador.getSelectedIndex());
            if (equipo.getPlantilla().size() < 4) {
                if (cb_posicion.getSelectedIndex() == 0) {
                    Portero portero = new Portero(nombreJ, edad, nacionalidad, pieH, equipo);
                    jugadores.add(portero);
                    equipos.get(cb_equipoJugador.getSelectedIndex()).getPlantilla().add(portero);
                    JOptionPane.showMessageDialog(this, "Portero agregado");
                    cb_eliminarJ.setModel(actualizarComboJugador());
                    cb_modificarJ.setModel(actualizarComboJugador());
                } else if (cb_posicion.getSelectedIndex() == 1) {
                    Defensa defensa = new Defensa(nombreJ, edad, nacionalidad, pieH, equipo);
                    jugadores.add(defensa);
                    equipos.get(cb_equipoJugador.getSelectedIndex()).getPlantilla().add(defensa);
                    JOptionPane.showMessageDialog(this, "Defensa agregado");
                    cb_eliminarJ.setModel(actualizarComboJugador());
                    cb_modificarJ.setModel(actualizarComboJugador());
                } else if (cb_posicion.getSelectedIndex() == 2) {
                    MedioCampista mediocampista = new MedioCampista(nombreJ, edad, nacionalidad, pieH, equipo);
                    jugadores.add(mediocampista);
                    equipos.get(cb_equipoJugador.getSelectedIndex()).getPlantilla().add(mediocampista);
                    JOptionPane.showMessageDialog(this, "Mediocampista agregado");
                    cb_eliminarJ.setModel(actualizarComboJugador());
                    cb_modificarJ.setModel(actualizarComboJugador());
                } else if (cb_posicion.getSelectedIndex() == 3) {
                    Delantero delantero = new Delantero(nombreJ, edad, nacionalidad, pieH, equipo);
                    jugadores.add(delantero);
                    equipos.get(cb_equipoJugador.getSelectedIndex()).getPlantilla().add(delantero);
                    JOptionPane.showMessageDialog(this, "Delantero agregado con exito");
                    cb_eliminarJ.setModel(actualizarComboJugador());
                    cb_modificarJ.setModel(actualizarComboJugador());
                }
            } else {
                JOptionPane.showMessageDialog(this, "Este equipo ya esta lleno");
            }

        }
    }//GEN-LAST:event_btn_agregarJMouseClicked

    private void btn_eliminarJMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_eliminarJMouseClicked
        if (cb_eliminarJ.getSelectedIndex() >= 0) {
            jugadores.remove(cb_eliminarJ.getSelectedIndex());
            cb_eliminarJ.setModel(actualizarComboJugador());
            cb_modificarJ.setModel(actualizarComboJugador());
        }
    }//GEN-LAST:event_btn_eliminarJMouseClicked

    private void bt_elminarEsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_elminarEsMouseClicked
        if (cb_eliminarEs.getSelectedIndex() >= 0) {
            estadios.remove(cb_eliminarEs.getSelectedIndex());
            JOptionPane.showMessageDialog(this, "Eliminado con exito");
            cb_eliminarEs.setModel(actualizarComboEstadio());

        }
    }//GEN-LAST:event_bt_elminarEsMouseClicked

    private void bt_actualizarEquipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_actualizarEquipoMouseClicked
        Table_equipo.setModel(actualizarTablaEquipo((DefaultTableModel) Table_equipo.getModel()));
    }//GEN-LAST:event_bt_actualizarEquipoMouseClicked

    private void bt_actualizarEstadioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_actualizarEstadioMouseClicked
        Table_estadio.setModel(actualizarTablaEstadio((DefaultTableModel) Table_estadio.getModel()));
    }//GEN-LAST:event_bt_actualizarEstadioMouseClicked

    private void bt_actualizarJugadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_actualizarJugadorMouseClicked
        Table_jugador.setModel(actualizarTablaJugador((DefaultTableModel) Table_jugador.getModel()));
    }//GEN-LAST:event_bt_actualizarJugadorMouseClicked

    private void bt_elminarEqMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_elminarEqMouseClicked
        if (cb_eliminarEq.getSelectedIndex() >= 0) {
            equipos.remove(cb_eliminarEq.getSelectedIndex());
            JOptionPane.showMessageDialog(this, "Eliminado con exito");
            cb_eliminarEq.setModel(actualizarComboEquipo());
            cb_modificarEq.setModel(actualizarComboEquipo());
            cb_equipos.setModel(actualizarComboEquipo());
            cb_equipos1.setModel(actualizarComboEquipo());
        }
    }//GEN-LAST:event_bt_elminarEqMouseClicked

    private void bt_modificarEqMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_modificarEqMouseClicked
        String nombreE = tf_nombreEquipo1.getText();
        String paisE = tf_paisEquipo1.getText();
        equipos.get(cb_modificarEq.getSelectedIndex()).setNombre(nombreE);
        equipos.get(cb_modificarEq.getSelectedIndex()).setPais(paisE);
        JOptionPane.showMessageDialog(this, "Modificado con exito");
        cb_eliminarEq.setModel(actualizarComboEquipo());
        cb_modificarEq.setModel(actualizarComboEquipo());
        cb_equipos.setModel(actualizarComboEquipo());
        cb_equipos1.setModel(actualizarComboEquipo());
        tf_nombreEquipo1.setText("");
        tf_paisEquipo1.setText("");
    }//GEN-LAST:event_bt_modificarEqMouseClicked

    private void btn_modificarJMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_modificarJMouseClicked
        String nombreJ = tf_nombreJ1.getText();
        int edad = Integer.parseInt(tf_edadJ1.getText());
        String nacionalidad = tf_nacionalidadJ1.getText();
        String pieH = tf_pieH1.getText();
        jugadores.get(cb_modificarJ.getSelectedIndex()).setNombre(nombreJ);
        jugadores.get(cb_modificarJ.getSelectedIndex()).setEdad(edad);
        jugadores.get(cb_modificarJ.getSelectedIndex()).setNacionalidad(nacionalidad);
        jugadores.get(cb_modificarJ.getSelectedIndex()).setPieH(pieH);
        JOptionPane.showMessageDialog(this, "Modificado con exito");
        cb_eliminarJ.setModel(actualizarComboJugador());
        cb_modificarJ.setModel(actualizarComboJugador());
    }//GEN-LAST:event_btn_modificarJMouseClicked

    private void btn_modificarEsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_modificarEsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_modificarEsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table_equipo;
    private javax.swing.JTable Table_estadio;
    private javax.swing.JTable Table_jugador;
    private javax.swing.JButton bt_actualizarEquipo;
    private javax.swing.JButton bt_actualizarEstadio;
    private javax.swing.JButton bt_actualizarJugador;
    private javax.swing.JButton bt_elminarEq;
    private javax.swing.JButton bt_elminarEs;
    private javax.swing.JButton bt_modificarEq;
    private javax.swing.JButton btn_agregarJ;
    private javax.swing.JButton btn_crearEs;
    private javax.swing.JButton btn_eliminarJ;
    private javax.swing.JButton btn_modificarEs;
    private javax.swing.JButton btn_modificarJ;
    private javax.swing.JComboBox<String> cb_eliminarEq;
    private javax.swing.JComboBox<String> cb_eliminarEs;
    private javax.swing.JComboBox<String> cb_eliminarJ;
    private javax.swing.JComboBox<String> cb_equipoJugador;
    private javax.swing.JComboBox<String> cb_equipos;
    private javax.swing.JComboBox<String> cb_equipos1;
    private javax.swing.JComboBox<String> cb_modificarEq;
    private javax.swing.JComboBox<String> cb_modificarEs;
    private javax.swing.JComboBox<String> cb_modificarJ;
    private javax.swing.JComboBox<String> cb_posicion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jb_crearEq;
    private javax.swing.JPanel panel_AgregarEq;
    private javax.swing.JPanel panel_AgregarEs;
    private javax.swing.JPanel panel_AgregarJ;
    private javax.swing.JPanel panel_EliminarEq;
    private javax.swing.JPanel panel_EliminarEs;
    private javax.swing.JPanel panel_EliminarJ;
    private javax.swing.JPanel panel_ListarEq;
    private javax.swing.JPanel panel_ListarEs;
    private javax.swing.JPanel panel_ListarJ;
    private javax.swing.JPanel panel_ModificarEq;
    private javax.swing.JPanel panel_ModificarEs;
    private javax.swing.JPanel panel_ModificarJ;
    private javax.swing.JTabbedPane tabbedpane;
    private javax.swing.JTextField tf_capacidadE;
    private javax.swing.JTextField tf_capacidadE1;
    private javax.swing.JTextField tf_ciudadEstadio;
    private javax.swing.JTextField tf_ciudadEstadio1;
    private javax.swing.JTextField tf_edadJ;
    private javax.swing.JTextField tf_edadJ1;
    private javax.swing.JTextField tf_nacionalidadJ;
    private javax.swing.JTextField tf_nacionalidadJ1;
    private javax.swing.JTextField tf_nombreEquipo;
    private javax.swing.JTextField tf_nombreEquipo1;
    private javax.swing.JTextField tf_nombreEstadio;
    private javax.swing.JTextField tf_nombreEstadio1;
    private javax.swing.JTextField tf_nombreJ;
    private javax.swing.JTextField tf_nombreJ1;
    private javax.swing.JTextField tf_paisEquipo;
    private javax.swing.JTextField tf_paisEquipo1;
    private javax.swing.JTextField tf_pieH;
    private javax.swing.JTextField tf_pieH1;
    // End of variables declaration//GEN-END:variables
}
